# 端口配置
server:
  port: 8080
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    # MySql配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sourdb?serverTimezone=UTC&characterEncoding=utf8&useSSL=false
    username: root
    password: yrO,cl:#x7y8
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true

  # freemarker配置
  freemarker:
    allow-request-override: false
    cache: false
    check-template-location: true
    charset: UTF-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    suffix: .ftlh
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
logging:
  file:
    name: logs/log.log
